# Generated by Django 5.1.2 on 2025-03-23 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DR', 'Черновик'), ('PB', 'Опубликовано')], default='DR', max_length=2, verbose_name='Статус изображения')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название изображения')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='Истечение срока')),
                ('perceptual_hash', models.CharField(max_length=64, verbose_name='Перцептивный хэш')),
                ('image_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к изображению')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser', verbose_name='Идентификатор пользователя')),
            ],
            options={
                'verbose_name': 'Темпоральное изображение',
                'verbose_name_plural': 'Темпоральные изображения',
                'db_table': 'temporal_images',
                'indexes': [models.Index(fields=['perceptual_hash'], name='temporal_im_percept_6350f8_idx'), models.Index(fields=['expiration_time'], name='temporal_im_expirat_af7b75_idx'), models.Index(fields=['user', 'status'], name='temporal_im_user_id_d73d85_idx')],
            },
        ),
    ]
