# Generated by Django 5.1.2 on 2025-03-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_temporalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalimage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название изображения'),
        ),
    ]
