# Generated by Django 5.1.2 on 2025-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_temporalimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporalimage',
            name='status',
            field=models.CharField(choices=[('DR', 'Черновик'), ('PB', 'Опубликовано'), ('AR', 'Архивные изображения')], default='DR', max_length=2, verbose_name='Статус изображения'),
        ),
    ]
